class AppLocalizations {
  static const String currentLanguage = 'en';

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'events': 'Events',
      'title': 'Title',
      'login': 'Login',
      'register': 'Register',
      'summary': 'Summary',
      'noData': 'No data',
      'pending': 'Pending',
      'noConflicts': 'No conflicts',
      'email': 'Email',
      'password': 'Password',
      'firstName': 'First name',
      'fillAllFields': 'Fill all fields',
      'min8Chars': 'Minimum 8 characters',
      'noAccountRegister': 'No account? Register',
      'pendingModeration': 'Pending Moderation',
      'retry': 'Retry',
      'noEventsPending': 'No events pending moderation',
      'description': 'Description',
      'itEquipment': 'IT Equipment',
      'materials': 'Materials',
      'openUrl': 'Open: ',
      'moderation': 'Moderation',
      'approve': 'Approve',
      'edits': 'Edits',
      'reject': 'Reject',
      'comment': 'Comment',
      'cancel': 'Cancel',
      'done': 'Done',
      'eventCalendar': 'Event Calendar',
      'bookings': 'BOOKINGS',
      'available': 'Available',
      'noApprovedBookings': 'No approved bookings for this day',
      'comingSoon': 'Coming soon',
      'myRequests': 'My requests',
      'noBookings': 'No requests',
      'coordinatorComment': 'Coordinator comment',
      'somethingWentWrong': 'Something went wrong',
      'newEvent': 'New event',
      'editEvent': 'Edit event',
      'dateTimeTab': 'Date & time',
      'basicTab': 'Basic',
      'resourcesTab': 'Resources',
      'close': 'Close',
      'requiredField': 'Required field',
      'selectCategory': 'Select category',
      'category': 'Category',
      'date': 'Date',
      'time': 'Start time',
      'place': 'Place',
      'registrationUrl': 'Registration URL',
      'back': 'Back',
      'next': 'Next',
      'sendRequest': 'Send request',
      'sent': 'Sent!',
      'moderationTimeframe':
          'Administrators will review within 1-2 business days.',
      'toEvents': 'To events',
      'itEquipmentHint': 'Projector, laptops, outlets...',
      'materialsHint': 'Markers, A4 paper, flipchart...',
      'analytics': 'Analytics',
      'categories': 'Categories',
      'categoriesSub': 'Where the flow of events is concentrated',
      'organizers': 'Organizers',
      'organizersSub': 'Who submits and hosts events most often',
      // ── coordinator analytics dashboard ──
      'overview': 'Overview',
      'moderationHealth': 'Moderation health',
      'engagement': 'Engagement',
      'ratings': 'Ratings',
      'failedToLoad': 'Failed to load',
      'nothingYet': 'Nothing here yet',
      'pendingReview': 'Pending review',
      'needsChanges': 'Needs changes',
      'rejected': 'Rejected',
      'cancelled': 'Cancelled',
      'archived': 'Archived',
      'publishedThisWeek': 'Published this week',
      'upcomingEvents': 'Upcoming',
      'avgRating': 'Avg rating',
      'totalFavorites': 'Favorites',
      'registrationClicks': 'Registrations',
      'eventViews': 'Views',
      'approvalRate': 'Approval rate',
      'rejectionRate': 'Rejection rate',
      'needsChangesRate': 'Needs-changes rate',
      'timeToFirstDecision': 'Time to first decision',
      'timeToFirstDecisionTip':
          'Average time from submission to the first coordinator decision.',
      'avgReviewTime': 'Avg review time',
      'avgReviewTimeTip':
          'Average time from submission to the final approve/reject, including any back-and-forth.',
      'avgIterations': 'Avg review passes',
      'avgIterationsTip':
          'Average number of coordinator review passes before an event is decided.',
      'queueSize': 'Queue size',
      'longestPending': 'Longest waiting',
      'waitingOver': 'Waiting over',
      'shares': 'Shares',
      'reminders': 'Reminders',
      'viewsOverTime': 'Views over time',
      'mostViewed': 'Most viewed',
      'topRated': 'Top rated',
      'lowestRated': 'Lowest rated',
      'ratingDistribution': 'Rating distribution',
      'totalReviews': 'Total reviews',
      'zeroReviews': 'Events with no reviews',
      'reviews': 'reviews',
      // ── period selector + event picker ──
      'period': 'Period',
      'last7Days': 'Last 7 days',
      'last30Days': 'Last 30 days',
      'last90Days': 'Last 90 days',
      'thisMonth': 'This month',
      'thisYear': 'This year',
      'allTime': 'All time',
      'customRange': 'Custom range',
      'allEvents': 'All events',
      'selectEvent': 'Select event',
      'searchEvents': 'Search events',
      'noEventsFound': 'No events found',
      'clearFilter': 'Clear filter',
      'slotConflicts': 'Slot conflicts',
      'slotConflictsSub':
          'Same date and location among approved and pending events',
      'pendingRequests': 'Pending requests',
      'pendingRequestsSub': 'Waiting for review',
      'totalEvents': 'Total events',
      'totalEventsSub': 'Approved events in the database',
      'approvedLabel': 'Approved',
      'pendingLabel': 'Under review',
      'needsChangesLabel': 'Needs edits',
      'rejectedLabel': 'Rejected',
      'cancelledLabel': 'Cancelled',
      'archivedLabel': 'Archived',
      'resubmitted': 'In review',
      'waitingForCreator': 'Waiting for creator',
      'readyForReview': 'Ready for review',
      'editAndResubmit': 'Edit & resubmit',
      'resubmittedBanner':
          'Submitted for review — waiting for moderator response.',
      'sorting': 'Sorting',
      'byDateClosest': 'Closest first',
      'byDateFurthest': 'Furthest first',
      'oldestFirst': 'Oldest requests first',
      'newestFirst': 'Newest requests first',
      'location': 'Location',
      'organizer': 'Organizer',
      'requests': 'Requests',
      'noRequestsUnderReview': 'No requests under review',
      'nothingFound': 'Nothing found',
      'search': 'Search',
      'approvedEventsAndRequests': 'Approved events and requests',
      'noEventsForDay': 'No events for this day',
      'request': 'Request',
      'calendar': 'Calendar',
      'noBookingsOrRequests': 'No bookings or requests for this day',
      'fillFields': 'Fill all fields',
      'min8': 'Minimum 8 characters',
      'passwordLabel': 'Password',
      'firstNameLabel': 'First name',
      'noAccount': 'No account? Register',
      'required': 'Required field',
      'specifyDate': 'Specify date',
      'specifyTime': 'Specify start time',
      'endTime': 'End time',
      'specifyEndTime': 'Specify end time',
    },
    'ru': {
      'events': 'Ивенты',
      'title': 'Название',
      'login': 'Войти',
      'register': 'Регистрация',
      'summary': 'Сводка',
      'noData': 'Нет данных',
      'pending': 'Ожидает',
      'noConflicts': 'Конфликтов нет',
      'email': 'Email',
      'password': 'Пароль',
      'firstName': 'Имя',
      'fillAllFields': 'Заполните все поля',
      'min8Chars': 'Минимум 8 символов',
      'noAccountRegister': 'Нет аккаунта? Зарегистрироваться',
      'pendingModeration': 'На модерации',
      'retry': 'Повторить',
      'noEventsPending': 'Нет заявок на модерации',
      'description': 'Описание',
      'itEquipment': 'IT-оборудование',
      'materials': 'Материалы',
      'openUrl': 'Открыть: ',
      'moderation': 'Модерация',
      'approve': 'Одобрить',
      'edits': 'Правки',
      'reject': 'Отклонить',
      'comment': 'Комментарий',
      'cancel': 'Отмена',
      'done': 'Готово',
      'eventCalendar': 'Календарь событий',
      'bookings': 'БРОНИРОВАНИЯ',
      'available': 'Свободно',
      'noApprovedBookings': 'На этот день нет одобренных броней',
      'comingSoon': 'Скоро появится',
      'myRequests': 'Мои заявки',
      'noBookings': 'Нет заявок',
      'coordinatorComment': 'Комментарий координатора',
      'somethingWentWrong': 'Что-то пошло не так',
      'newEvent': 'Новое мероприятие',
      'editEvent': 'Редактировать мероприятие',
      'dateTimeTab': 'Дата и время',
      'basicTab': 'Основное',
      'resourcesTab': 'Ресурсы',
      'close': 'Закрыть',
      'requiredField': 'Обязательное поле',
      'selectCategory': 'Выберите категорию',
      'category': 'Категория',
      'date': 'Дата',
      'time': 'Время начала',
      'place': 'Место',
      'registrationUrl': 'Ссылка на регистрацию',
      'back': 'Назад',
      'next': 'Далее',
      'sendRequest': 'Отправить заявку',
      'sent': 'Отправлено!',
      'moderationTimeframe':
          'Администраторы рассмотрят в течение 1–2 рабочих дней.',
      'toEvents': 'К ивентам',
      'itEquipmentHint': 'Проектор, ноутбуки, розетки...',
      'materialsHint': 'Маркеры, бумага А4, флипчарт...',
      'analytics': 'Аналитика',
      'categories': 'Категории',
      'categoriesSub': 'Где сосредоточен поток событий',
      'organizers': 'Организаторы',
      'organizersSub': 'Кто чаще всего подаёт и проводит события',
      'slotConflicts': 'Конфликты слотов',
      'slotConflictsSub':
          'Одинаковая дата и локация среди одобренных и ожидающих событий',
      'pendingRequests': 'Заявки на модерации',
      'pendingRequestsSub': 'Ожидают рассмотрения',
      'totalEvents': 'Всего событий',
      'totalEventsSub': 'Одобренные события в базе данных',
      'approvedLabel': 'Одобрено',
      'pendingLabel': 'На модерации',
      'needsChangesLabel': 'Требуются правки',
      'rejectedLabel': 'Отклонено',
      'cancelledLabel': 'Отменено',
      'archivedLabel': 'В архиве',
      'resubmitted': 'На проверке',
      'waitingForCreator': 'Ожидает автора',
      'readyForReview': 'Готово к проверке',
      'editAndResubmit': 'Изменить и отправить',
      'resubmittedBanner':
          'Отправлено на проверку — ожидается ответ модератора.',
      'sorting': 'Сортировка',
      'byDateClosest': 'Сначала ближайшие',
      'byDateFurthest': 'Сначала дальние',
      'oldestFirst': 'Сначала первые заявки',
      'newestFirst': 'Сначала последние заявки',
      'location': 'Локация',
      'organizer': 'Организатор',
      'requests': 'Заявки',
      'noRequestsUnderReview': 'Нет заявок на рассмотрении',
      'nothingFound': 'Ничего не найдено',
      'search': 'Поиск',
      'approvedEventsAndRequests': 'Одобренные события и заявки',
      'noEventsForDay': 'На этот день событий нет',
      'request': 'Заявка',
      'calendar': 'Календарь',
      'noBookingsOrRequests': 'На этот день нет броней или заявок',
      'fillFields': 'Заполните все поля',
      'min8': 'Минимум 8 символов',
      'passwordLabel': 'Пароль',
      'firstNameLabel': 'Имя',
      'noAccount': 'Нет аккаунта? Зарегистрироваться',
      'required': 'Обязательное поле',
      'specifyDate': 'Укажите дату',
      'specifyTime': 'Укажите время начала',
      'endTime': 'Время окончания',
      'specifyEndTime': 'Укажите время окончания',
    },
    'kk': {
      'events': 'Ивенттер',
      'title': 'Атауы',
      'login': 'Кіру',
      'register': 'Тіркелу',
      'summary': 'Жиынтық',
      'noData': 'Деректер жоқ',
      'pending': 'Күтілуде',
      'noConflicts': 'Қақтығыстар жоқ',
      'email': 'Email',
      'password': 'Құпия сөз',
      'firstName': 'Аты',
      'fillAllFields': 'Барлық өрістерді толтырыңыз',
      'min8Chars': 'Кемінде 8 таңба',
      'noAccountRegister': 'Тіркелгіңіз жоқ па? Тіркелу',
      'pendingModeration': 'Модерацияда',
      'retry': 'Қайталау',
      'noEventsPending': 'Модерациядағы сұранымдар жоқ',
      'description': 'Сипаттамасы',
      'itEquipment': 'IT-жабдықтар',
      'materials': 'Материалдар',
      'openUrl': 'Ашу: ',
      'moderation': 'Модерация',
      'approve': 'Мақұлдау',
      'edits': 'Түзетулер',
      'reject': 'Бас тарту',
      'comment': 'Түсініктеме',
      'cancel': 'Бас тарту',
      'done': 'Дайын',
      'eventCalendar': 'Іс-шаралар күнтізбесі',
      'bookings': 'БРОНДАУЛАР',
      'available': 'Бос',
      'noApprovedBookings': 'Бұл күнге мақұлданған брондаулар жоқ',
      'comingSoon': 'Жақында пайда болады',
      'myRequests': 'Менің сұранымдарым',
      'noBookings': 'Сұранымдар жоқ',
      'coordinatorComment': 'Үйлестірушінің түсініктемесі',
      'somethingWentWrong': 'Бірдеңе дұрыс болмады',
      'newEvent': 'Жаңа іс-шара',
      'editEvent': 'Іс-шараны өңдеу',
      'dateTimeTab': 'Күні мен уақыты',
      'basicTab': 'Негізгі',
      'resourcesTab': 'Ресурстар',
      'close': 'Жабу',
      'requiredField': 'Міндетті өріс',
      'selectCategory': 'Санатты таңдаңыз',
      'category': 'Санат',
      'date': 'Күні',
      'time': 'Басталу уақыты',
      'place': 'Орыны',
      'registrationUrl': 'Тіркелу сілтемесі',
      'back': 'Артқа',
      'next': 'Келесі',
      'sendRequest': 'Сұранымды жіберу',
      'sent': 'Жіберілді!',
      'moderationTimeframe': 'Әкімшілер 1-2 жұмыс күні ішінде қарастырады.',
      'toEvents': 'Іс-шараларға',
      'itEquipmentHint': 'Проектор, ноутбуктер, розеткалар...',
      'materialsHint': 'Маркерлер, А4 қағазы, флипчарт...',
      'analytics': 'Аналитика',
      'categories': 'Санаттар',
      'categoriesSub': 'Іс-шаралар ағыны шоғырланған жер',
      'organizers': 'Ұйымдастырушылар',
      'organizersSub': 'Кім іс-шараларды жиі жібереді және өткізеді',
      'slotConflicts': 'Слоттардың қақтығысы',
      'slotConflictsSub':
          'Мақұлданған және күтудегі іс-шаралардың күні мен орны бірдей',
      'pendingRequests': 'Модерациядағы сұранымдар',
      'pendingRequestsSub': 'Қарауды күтуде',
      'totalEvents': 'Барлық іс-шаралар',
      'totalEventsSub': 'Деректер қорындағы мақұлданған іс-шаралар',
      'approvedLabel': 'Мақұлданды',
      'pendingLabel': 'Модерацияда',
      'needsChangesLabel': 'Түзетулер қажет',
      'rejectedLabel': 'Қабылданбады',
      'cancelledLabel': 'Болдырылмады',
      'archivedLabel': 'Мұрағатталды',
      'resubmitted': 'Тексеруде',
      'waitingForCreator': 'Авторды күтуде',
      'readyForReview': 'Тексеруге дайын',
      'editAndResubmit': 'Өңдеп қайта жіберу',
      'resubmittedBanner': 'Тексеруге жіберілді — модератордың жауабын күтуде.',
      'sorting': 'Сұрыптау',
      'byDateClosest': 'Ең жақын бірінші',
      'byDateFurthest': 'Ең алыс бірінші',
      'oldestFirst': 'Алдымен алғашқы өтініштер',
      'newestFirst': 'Алдымен соңғы өтініштер',
      'location': 'Орыны',
      'organizer': 'Ұйымдастырушы',
      'requests': 'Сұранымдар',
      'noRequestsUnderReview': 'Қарастырылып жатқан сұранымдар жоқ',
      'nothingFound': 'Ештеңе табылмады',
      'search': 'Іздеу',
      'approvedEventsAndRequests': 'Мақұлданған іс-шаралар мен сұранымдар',
      'noEventsForDay': 'Бұл күнге іс-шаралар жоқ',
      'request': 'Сұраным',
      'calendar': 'Күнтізбе',
      'noBookingsOrRequests': 'Бұл күнге брондау немесе сұранымдар жоқ',
      'fillFields': 'Барлық өрістерді толтырыңыз',
      'min8': 'Кемінде 8 таңба',
      'passwordLabel': 'Құпия сөз',
      'firstNameLabel': 'Аты',
      'noAccount': 'Тіркелгіңіз жоқ па? Тіркелу',
      'required': 'Міндетті өріс',
      'specifyDate': 'Күнді көрсетіңіз',
      'specifyTime': 'Басталу уақытын көрсетіңіз',
      'endTime': 'Аяқталу уақыты',
      'specifyEndTime': 'Аяқталу уақытын көрсетіңіз',
    },
  };

  static String get(String key) {
    return _localizedValues[currentLanguage]?[key] ?? key;
  }
}
