class AppLocalizations {
  static const String currentLanguage = 'en';

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'coverImage': 'Cover Image',
      'addCover': 'Add Cover',
      'replace': 'Replace',
      'remove': 'Remove',
      'replaceCover': 'Replace cover?',
      'replaceCoverConfirm': 'This will replace the current cover image.',
      'removeCover': 'Remove cover?',
      'removeCoverConfirm': 'This will remove the cover from the event.',
      'uploading': 'Uploading…',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'coverStillUploading': 'Please wait for the cover to finish uploading.',
      'coverPickFailed': 'Could not open the image. Please try again.',
      'coverUnsupported': 'Unsupported image. Use JPEG, PNG, WebP or GIF.',
      'coverUploadFailed': 'Cover upload failed. Please retry.',
      'events': 'Events',
      'event': 'Event',
      'title': 'Title',
      'login': 'Login',
      'register': 'Register',
      'summary': 'Summary',
      'noData': 'No data',
      'pending': 'Pending',
      'noConflicts': 'No conflicts',
      'email': 'Email',
      'password': 'Password',
      'firstName': 'First name',
      'fillAllFields': 'Fill all fields',
      'min8Chars': 'Minimum 8 characters',
      'noAccountRegister': 'No account? Register',
      'pendingModeration': 'Pending Moderation',
      'retry': 'Retry',
      'noEventsPending': 'No events pending moderation',
      'description': 'Description',
      'itEquipment': 'IT Equipment',
      'materials': 'Materials',
      'openUrl': 'Open: ',
      'moderation': 'Moderation',
      'approve': 'Approve',
      'edits': 'Edits',
      'reject': 'Reject',
      'comment': 'Comment',
      'cancel': 'Cancel',
      'done': 'Done',
      'unsavedChanges': 'Unsaved changes',
      'unsavedChangesMessage': 'Discard the changes to this event?',
      'keepEditing': 'Keep editing',
      'discard': 'Discard',
      'submissionInProgress': 'Please wait while the event is being submitted.',
      'eventCalendar': 'Event Calendar',
      'bookings': 'BOOKINGS',
      'available': 'Available',
      'noApprovedBookings': 'No approved bookings for this day',
      'comingSoon': 'Coming soon',
      'myRequests': 'My requests',
      'noBookings': 'No requests',
      'coordinatorComment': 'Coordinator comment',
      'somethingWentWrong': 'Something went wrong',
      'networkUnavailable': 'No connection. Check your network and try again.',
      'newEvent': 'New event',
      'editEvent': 'Edit event',
      'dateTimeTab': 'Date & time',
      'basicTab': 'Basic',
      'resourcesTab': 'Resources',
      'close': 'Close',
      'requiredField': 'Required field',
      'selectCategory': 'Select category',
      'category': 'Category',
      'date': 'Date',
      'time': 'Start time',
      'place': 'Place',
      'registrationUrl': 'Registration URL',
      'back': 'Back',
      'next': 'Next',
      'sendRequest': 'Send request',
      'sent': 'Sent!',
      'moderationTimeframe':
          'Administrators will review within 1-2 business days.',
      'toEvents': 'To events',
      'itEquipmentHint': 'Projector, laptops, outlets...',
      'materialsHint': 'Markers, A4 paper, flipchart...',
      'analytics': 'Analytics',
      'categories': 'Categories',
      'categoriesSub': 'Where the flow of events is concentrated',
      'organizers': 'Organizers',
      'organizersSub': 'Who submits and hosts events most often',
      // ── coordinator analytics dashboard ──
      'overview': 'Overview',
      'moderationHealth': 'Moderation health',
      'engagement': 'Engagement',
      'ratings': 'Ratings',
      'failedToLoad': 'Failed to load',
      'nothingYet': 'Nothing here yet',
      'pendingReview': 'Pending review',
      'needsChanges': 'Needs changes',
      'rejected': 'Rejected',
      'cancelled': 'Cancelled',
      'archived': 'Archived',
      'publishedThisWeek': 'Published',
      'upcomingEvents': 'Upcoming',
      'avgRating': 'Avg rating',
      'totalFavorites': 'Favorites',
      'registrationClicks': 'Registrations',
      'eventViews': 'Views',
      'approvalRate': 'Approval rate',
      'rejectionRate': 'Rejection rate',
      'needsChangesRate': 'Needs-changes rate',
      'timeToFirstDecision': 'Avg time to first decision',
      'timeToFirstDecisionTip':
          'Average time from submission to the first coordinator decision.',
      'avgReviewTime': 'Avg review time',
      'avgReviewTimeTip':
          'Average time from submission to the final approve/reject, including any back-and-forth.',
      'avgIterations': 'Avg review passes',
      'avgIterationsTip':
          'Average number of coordinator review passes before an event is decided.',
      'queueSize': 'Queue size',
      'longestPending': 'Longest waiting',
      'waitingOver': 'Waiting over',
      'shares': 'Shares',
      'reminders': 'Reminders',
      'viewsOverTime': 'Views over time',
      'mostViewed': 'Most viewed',
      'topRated': 'Top rated',
      'lowestRated': 'Lowest rated',
      'ratingDistribution': 'Rating distribution',
      'totalReviews': 'Total reviews',
      'zeroReviews': 'Events with no reviews',
      'reviews': 'reviews',
      // ── period selector + event picker ──
      'period': 'Period',
      'last7Days': 'Last 7 days',
      'last30Days': 'Last 30 days',
      'last90Days': 'Last 90 days',
      'thisMonth': 'This month',
      'thisYear': 'This year',
      'allTime': 'All time',
      'customRange': 'Custom range',
      'custom': 'Custom',
      'apply': 'Apply',
      'allEvents': 'All events',
      'allCategories': 'All categories',
      'allOrganizers': 'All organizers',
      'showAll': 'Show all',
      'peak': 'Peak',
      'noActivityInPeriod': 'No activity in this period',
      // ── per-event moderation detail ──
      'submittedAction': 'Submitted',
      'restoredAction': 'Restored',
      'editedAction': 'Edited',
      'currentStatus': 'Current status',
      'submittedAt': 'Submitted at',
      'firstReviewedAt': 'First reviewed at',
      'approvedAt': 'Approved at',
      'rejectedAt': 'Rejected at',
      'totalReviewTime': 'Total review time',
      'reviewIterations': 'Review iterations',
      'needsChangesCount': 'Changes requested',
      'resubmissionCount': 'Resubmissions',
      'latestModerator': 'Last reviewed by',
      'latestComment': 'Moderator comment',
      'lastStatusUpdate': 'Last updated',
      'creatorResubmitted': 'Creator resubmitted',
      'moderationTimeline': 'Timeline',
      'moderationCounts': 'Counts',
      'yes': 'Yes',
      'no': 'No',
      // ── reviews sheet ──
      'viewReviews': 'View reviews',
      'allReviews': 'All reviews',
      'noReviewsYet': 'No reviews yet',
      'selectEvent': 'Select event',
      'searchEvents': 'Search events',
      'noEventsFound': 'No events found',
      'clearFilter': 'Clear filter',
      'slotConflicts': 'Slot conflicts',
      'slotConflictsSub':
          'Same date and location among approved and pending events',
      'pendingRequests': 'Pending requests',
      'pendingRequestsSub': 'Waiting for review',
      'totalEvents': 'Total events',
      'totalEventsSub': 'Approved events in the database',
      'approvedLabel': 'Approved',
      'pendingLabel': 'Under review',
      'needsChangesLabel': 'Needs edits',
      'rejectedLabel': 'Rejected',
      'cancelledLabel': 'Cancelled',
      'archivedLabel': 'Archived',
      'resubmitted': 'In review',
      'waitingForCreator': 'Waiting for creator',
      'readyForReview': 'Ready for review',
      'editAndResubmit': 'Edit & resubmit',
      'resubmittedBanner':
          'Submitted for review — waiting for moderator response.',
      'sorting': 'Sorting',
      'byDateClosest': 'Upcoming',
      'byDateFurthest': 'Past',
      'oldestFirst': 'Oldest requests first',
      'newestFirst': 'Newest requests first',
      'location': 'Location',
      'organizer': 'Organizer',
      'requests': 'Requests',
      'noRequestsUnderReview': 'No requests under review',
      'nothingFound': 'Nothing found',
      'search': 'Search',
      'approvedEventsAndRequests': 'Approved events and requests',
      'noEventsForDay': 'No events for this day',
      'request': 'Request',
      'calendar': 'Calendar',
      'noBookingsOrRequests': 'No bookings or requests for this day',
      'fillFields': 'Fill all fields',
      'min8': 'Minimum 8 characters',
      'passwordLabel': 'Password',
      'firstNameLabel': 'First name',
      'noAccount': 'No account? Register',
      'required': 'Required field',
      'specifyDate': 'Specify date',
      'specifyTime': 'Specify start time',
      'endTime': 'End time',
      'specifyEndTime': 'Specify end time',
      'offlineShowingCached': 'Offline — showing saved data',
    },
    'ru': {
      'coverImage': 'Обложка',
      'addCover': 'Добавить обложку',
      'replace': 'Заменить',
      'remove': 'Удалить',
      'replaceCover': 'Заменить обложку?',
      'replaceCoverConfirm': 'Текущая обложка будет заменена.',
      'removeCover': 'Удалить обложку?',
      'removeCoverConfirm': 'Обложка будет удалена из события.',
      'uploading': 'Загрузка…',
      'gallery': 'Галерея',
      'camera': 'Камера',
      'coverStillUploading': 'Подождите, пока обложка загрузится.',
      'coverPickFailed': 'Не удалось открыть изображение. Попробуйте снова.',
      'coverUnsupported': 'Формат не поддерживается. JPEG, PNG, WebP или GIF.',
      'coverUploadFailed': 'Не удалось загрузить обложку. Повторите.',
      'events': 'Ивенты',
      'event': 'Ивент',
      'title': 'Название',
      'login': 'Войти',
      'register': 'Регистрация',
      'summary': 'Сводка',
      'noData': 'Нет данных',
      'pending': 'Ожидает',
      'noConflicts': 'Конфликтов нет',
      'email': 'Email',
      'password': 'Пароль',
      'firstName': 'Имя',
      'fillAllFields': 'Заполните все поля',
      'min8Chars': 'Минимум 8 символов',
      'noAccountRegister': 'Нет аккаунта? Зарегистрироваться',
      'pendingModeration': 'На модерации',
      'retry': 'Повторить',
      'noEventsPending': 'Нет заявок на модерации',
      'description': 'Описание',
      'itEquipment': 'IT-оборудование',
      'materials': 'Материалы',
      'openUrl': 'Открыть: ',
      'moderation': 'Модерация',
      'approve': 'Одобрить',
      'edits': 'Правки',
      'reject': 'Отклонить',
      'comment': 'Комментарий',
      'cancel': 'Отмена',
      'done': 'Готово',
      'unsavedChanges': 'Несохранённые изменения',
      'unsavedChangesMessage': 'Не сохранять изменения этого события?',
      'keepEditing': 'Продолжить редактирование',
      'discard': 'Не сохранять',
      'submissionInProgress': 'Подождите, пока событие отправляется.',
      'eventCalendar': 'Календарь событий',
      'bookings': 'БРОНИРОВАНИЯ',
      'available': 'Свободно',
      'noApprovedBookings': 'На этот день нет одобренных броней',
      'comingSoon': 'Скоро появится',
      'myRequests': 'Мои заявки',
      'noBookings': 'Нет заявок',
      'coordinatorComment': 'Комментарий координатора',
      'somethingWentWrong': 'Что-то пошло не так',
      'networkUnavailable':
          'Нет соединения. Проверьте интернет и повторите попытку.',
      'newEvent': 'Новое мероприятие',
      'editEvent': 'Редактировать мероприятие',
      'dateTimeTab': 'Дата и время',
      'basicTab': 'Основное',
      'resourcesTab': 'Ресурсы',
      'close': 'Закрыть',
      'requiredField': 'Обязательное поле',
      'selectCategory': 'Выберите категорию',
      'category': 'Категория',
      'date': 'Дата',
      'time': 'Время начала',
      'place': 'Место',
      'registrationUrl': 'Ссылка на регистрацию',
      'back': 'Назад',
      'next': 'Далее',
      'sendRequest': 'Отправить заявку',
      'sent': 'Отправлено!',
      'moderationTimeframe':
          'Администраторы рассмотрят в течение 1–2 рабочих дней.',
      'toEvents': 'К ивентам',
      'itEquipmentHint': 'Проектор, ноутбуки, розетки...',
      'materialsHint': 'Маркеры, бумага А4, флипчарт...',
      'analytics': 'Аналитика',
      'categories': 'Категории',
      'categoriesSub': 'Где сосредоточен поток событий',
      'organizers': 'Организаторы',
      'organizersSub': 'Кто чаще всего подаёт и проводит события',
      'slotConflicts': 'Конфликты слотов',
      'slotConflictsSub':
          'Одинаковая дата и локация среди одобренных и ожидающих событий',
      'pendingRequests': 'Заявки на модерации',
      'pendingRequestsSub': 'Ожидают рассмотрения',
      'totalEvents': 'Всего событий',
      'totalEventsSub': 'Одобренные события в базе данных',
      'approvedLabel': 'Одобрено',
      'pendingLabel': 'На модерации',
      'needsChangesLabel': 'Требуются правки',
      'rejectedLabel': 'Отклонено',
      'cancelledLabel': 'Отменено',
      'archivedLabel': 'В архиве',
      'resubmitted': 'На проверке',
      'waitingForCreator': 'Ожидает автора',
      'readyForReview': 'Готово к проверке',
      'editAndResubmit': 'Изменить и отправить',
      'resubmittedBanner':
          'Отправлено на проверку — ожидается ответ модератора.',
      'sorting': 'Сортировка',
      'byDateClosest': 'Предстоящие',
      'byDateFurthest': 'Прошедшие',
      'oldestFirst': 'Сначала первые заявки',
      'newestFirst': 'Сначала последние заявки',
      'location': 'Локация',
      'organizer': 'Организатор',
      'requests': 'Заявки',
      'noRequestsUnderReview': 'Нет заявок на рассмотрении',
      'nothingFound': 'Ничего не найдено',
      'search': 'Поиск',
      'approvedEventsAndRequests': 'Одобренные события и заявки',
      'noEventsForDay': 'На этот день событий нет',
      'request': 'Заявка',
      'calendar': 'Календарь',
      'noBookingsOrRequests': 'На этот день нет броней или заявок',
      'fillFields': 'Заполните все поля',
      'min8': 'Минимум 8 символов',
      'passwordLabel': 'Пароль',
      'firstNameLabel': 'Имя',
      'noAccount': 'Нет аккаунта? Зарегистрироваться',
      'required': 'Обязательное поле',
      'specifyDate': 'Укажите дату',
      'specifyTime': 'Укажите время начала',
      'endTime': 'Время окончания',
      'specifyEndTime': 'Укажите время окончания',
      'custom': 'Custom',
      'apply': 'Применить',
      // ── per-event moderation detail ──
      'submittedAction': 'Подано',
      'restoredAction': 'Восстановлено',
      'editedAction': 'Изменено',
      'currentStatus': 'Текущий статус',
      'submittedAt': 'Подано',
      'firstReviewedAt': 'Первая проверка',
      'approvedAt': 'Одобрено',
      'rejectedAt': 'Отклонено',
      'totalReviewTime': 'Общее время проверки',
      'reviewIterations': 'Итераций проверки',
      'needsChangesCount': 'Запросов правок',
      'resubmissionCount': 'Повторных подач',
      'latestModerator': 'Последний модератор',
      'latestComment': 'Комментарий модератора',
      'lastStatusUpdate': 'Последнее обновление',
      'creatorResubmitted': 'Автор повторно подал',
      'moderationTimeline': 'Хронология',
      'moderationCounts': 'Счётчики',
      'yes': 'Да',
      'no': 'Нет',
      // ── reviews sheet ──
      'viewReviews': 'Все отзывы',
      'allReviews': 'Все отзывы',
      'noReviewsYet': 'Отзывов пока нет',
      'offlineShowingCached': 'Оффлайн — показаны сохранённые данные',
    },
    'kk': {
      'coverImage': 'Мұқаба суреті',
      'addCover': 'Мұқаба қосу',
      'replace': 'Ауыстыру',
      'remove': 'Жою',
      'replaceCover': 'Мұқабаны ауыстырасыз ба?',
      'replaceCoverConfirm': 'Қазіргі мұқаба ауыстырылады.',
      'removeCover': 'Мұқабаны жоясыз ба?',
      'removeCoverConfirm': 'Мұқаба оқиғадан жойылады.',
      'uploading': 'Жүктелуде…',
      'gallery': 'Галерея',
      'camera': 'Камера',
      'coverStillUploading': 'Мұқаба жүктелгенше күте тұрыңыз.',
      'coverPickFailed': 'Суретті ашу мүмкін болмады. Қайталап көріңіз.',
      'coverUnsupported': 'Қолдау көрсетілмейді. JPEG, PNG, WebP немесе GIF.',
      'coverUploadFailed': 'Мұқабаны жүктеу сәтсіз аяқталды. Қайталаңыз.',
      'events': 'Ивенттер',
      'title': 'Атауы',
      'login': 'Кіру',
      'register': 'Тіркелу',
      'summary': 'Жиынтық',
      'noData': 'Деректер жоқ',
      'pending': 'Күтілуде',
      'noConflicts': 'Қақтығыстар жоқ',
      'email': 'Email',
      'password': 'Құпия сөз',
      'firstName': 'Аты',
      'fillAllFields': 'Барлық өрістерді толтырыңыз',
      'min8Chars': 'Кемінде 8 таңба',
      'noAccountRegister': 'Тіркелгіңіз жоқ па? Тіркелу',
      'pendingModeration': 'Модерацияда',
      'retry': 'Қайталау',
      'noEventsPending': 'Модерациядағы сұранымдар жоқ',
      'description': 'Сипаттамасы',
      'itEquipment': 'IT-жабдықтар',
      'materials': 'Материалдар',
      'openUrl': 'Ашу: ',
      'moderation': 'Модерация',
      'approve': 'Мақұлдау',
      'edits': 'Түзетулер',
      'reject': 'Бас тарту',
      'comment': 'Түсініктеме',
      'cancel': 'Бас тарту',
      'done': 'Дайын',
      'unsavedChanges': 'Сақталмаған өзгерістер',
      'unsavedChangesMessage':
          'Іс-шараға енгізілген өзгерістер сақталмасын ба?',
      'keepEditing': 'Өңдеуді жалғастыру',
      'discard': 'Сақтамай шығу',
      'submissionInProgress': 'Іс-шара жіберілгенше күте тұрыңыз.',
      'eventCalendar': 'Іс-шаралар күнтізбесі',
      'bookings': 'БРОНДАУЛАР',
      'available': 'Бос',
      'noApprovedBookings': 'Бұл күнге мақұлданған брондаулар жоқ',
      'comingSoon': 'Жақында пайда болады',
      'myRequests': 'Менің сұранымдарым',
      'noBookings': 'Сұранымдар жоқ',
      'coordinatorComment': 'Үйлестірушінің түсініктемесі',
      'somethingWentWrong': 'Бірдеңе дұрыс болмады',
      'networkUnavailable':
          'Байланыс жоқ. Интернетті тексеріп, қайталап көріңіз.',
      'newEvent': 'Жаңа іс-шара',
      'editEvent': 'Іс-шараны өңдеу',
      'dateTimeTab': 'Күні мен уақыты',
      'basicTab': 'Негізгі',
      'resourcesTab': 'Ресурстар',
      'close': 'Жабу',
      'requiredField': 'Міндетті өріс',
      'selectCategory': 'Санатты таңдаңыз',
      'category': 'Санат',
      'date': 'Күні',
      'time': 'Басталу уақыты',
      'place': 'Орыны',
      'registrationUrl': 'Тіркелу сілтемесі',
      'back': 'Артқа',
      'next': 'Келесі',
      'sendRequest': 'Сұранымды жіберу',
      'sent': 'Жіберілді!',
      'moderationTimeframe': 'Әкімшілер 1-2 жұмыс күні ішінде қарастырады.',
      'toEvents': 'Іс-шараларға',
      'itEquipmentHint': 'Проектор, ноутбуктер, розеткалар...',
      'materialsHint': 'Маркерлер, А4 қағазы, флипчарт...',
      'analytics': 'Аналитика',
      'categories': 'Санаттар',
      'categoriesSub': 'Іс-шаралар ағыны шоғырланған жер',
      'organizers': 'Ұйымдастырушылар',
      'organizersSub': 'Кім іс-шараларды жиі жібереді және өткізеді',
      'slotConflicts': 'Слоттардың қақтығысы',
      'slotConflictsSub':
          'Мақұлданған және күтудегі іс-шаралардың күні мен орны бірдей',
      'pendingRequests': 'Модерациядағы сұранымдар',
      'pendingRequestsSub': 'Қарауды күтуде',
      'totalEvents': 'Барлық іс-шаралар',
      'totalEventsSub': 'Деректер қорындағы мақұлданған іс-шаралар',
      'approvedLabel': 'Мақұлданды',
      'pendingLabel': 'Модерацияда',
      'needsChangesLabel': 'Түзетулер қажет',
      'rejectedLabel': 'Қабылданбады',
      'cancelledLabel': 'Болдырылмады',
      'archivedLabel': 'Мұрағатталды',
      'resubmitted': 'Тексеруде',
      'waitingForCreator': 'Авторды күтуде',
      'readyForReview': 'Тексеруге дайын',
      'editAndResubmit': 'Өңдеп қайта жіберу',
      'resubmittedBanner': 'Тексеруге жіберілді — модератордың жауабын күтуде.',
      'sorting': 'Сұрыптау',
      'byDateClosest': 'Алдағы',
      'byDateFurthest': 'Өткен',
      'oldestFirst': 'Алдымен алғашқы өтініштер',
      'newestFirst': 'Алдымен соңғы өтініштер',
      'location': 'Орыны',
      'organizer': 'Ұйымдастырушы',
      'requests': 'Сұранымдар',
      'noRequestsUnderReview': 'Қарастырылып жатқан сұранымдар жоқ',
      'nothingFound': 'Ештеңе табылмады',
      'search': 'Іздеу',
      'approvedEventsAndRequests': 'Мақұлданған іс-шаралар мен сұранымдар',
      'noEventsForDay': 'Бұл күнге іс-шаралар жоқ',
      'request': 'Сұраным',
      'calendar': 'Күнтізбе',
      'noBookingsOrRequests': 'Бұл күнге брондау немесе сұранымдар жоқ',
      'fillFields': 'Барлық өрістерді толтырыңыз',
      'min8': 'Кемінде 8 таңба',
      'passwordLabel': 'Құпия сөз',
      'firstNameLabel': 'Аты',
      'noAccount': 'Тіркелгіңіз жоқ па? Тіркелу',
      'required': 'Міндетті өріс',
      'specifyDate': 'Күнді көрсетіңіз',
      'specifyTime': 'Басталу уақытын көрсетіңіз',
      'endTime': 'Аяқталу уақыты',
      'specifyEndTime': 'Аяқталу уақытын көрсетіңіз',
      // ── per-event moderation detail ──
      'submittedAction': 'Берілді',
      'restoredAction': 'Қалпына келтірілді',
      'editedAction': 'Өзгертілді',
      'currentStatus': 'Ағымдағы мәртебе',
      'submittedAt': 'Берілген уақыт',
      'firstReviewedAt': 'Алғаш тексерілді',
      'approvedAt': 'Мақұлданған уақыт',
      'rejectedAt': 'Қабылданбаған уақыт',
      'totalReviewTime': 'Жалпы тексеру уақыты',
      'reviewIterations': 'Тексеру қайталануы',
      'needsChangesCount': 'Түзету сұраулары',
      'resubmissionCount': 'Қайта жіберулер',
      'latestModerator': 'Соңғы модератор',
      'latestComment': 'Модератор түсініктемесі',
      'lastStatusUpdate': 'Соңғы жаңарту',
      'creatorResubmitted': 'Автор қайта жіберді',
      'moderationTimeline': 'Хронология',
      'moderationCounts': 'Санаулар',
      'yes': 'Иә',
      'no': 'Жоқ',
      // ── reviews sheet ──
      'viewReviews': 'Барлық пікірлер',
      'allReviews': 'Барлық пікірлер',
      'noReviewsYet': 'Пікірлер әлі жоқ',
    },
  };

  static String get(String key) {
    return _localizedValues[currentLanguage]?[key] ?? key;
  }
}
