"""add registration_message_id to chats

Revision ID: 221e6b374de2
Revises: 9c13158a22e8
Create Date: 2026-05-01 14:00:15.242804
"""

from typing import Sequence, Union




revision: str = '221e6b374de2'
down_revision: Union[str, None] = '9c13158a22e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
