"""Admin panel and audit features

Revision ID: 2f1f82a9a6c0
Revises: 5ae7877410de
Create Date: 2026-05-31 00:21:52.580406
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2f1f82a9a6c0'
down_revision: Union[str, None] = '5ae7877410de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_target_type_target_id', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activity_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_logs'))
    )
    op.create_index('ix_user_activity_logs_action', 'user_activity_logs', ['action'], unique=False)
    op.create_index('ix_user_activity_logs_user_id', 'user_activity_logs', ['user_id'], unique=False)
    op.add_column('comments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True))
    op.add_column('comments', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.create_foreign_key(op.f('fk_comments_deleted_by_user_id_users'), 'comments', 'users', ['deleted_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_events_average_rating'), table_name='events')
    op.drop_index(op.f('ix_events_rating_count'), table_name='events')
    op.drop_column('events', 'average_rating')
    op.drop_column('events', 'rating_count')
    op.add_column('ratings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ratings', sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True))
    op.add_column('ratings', sa.Column('delete_reason', sa.String(length=255), nullable=True))
    op.create_foreign_key(op.f('fk_ratings_deleted_by_user_id_users'), 'ratings', 'users', ['deleted_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('role', sa.String(length=32), server_default='user', nullable=False))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('blocked_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('blocked_by_admin_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_users_blocked_by_admin_id_users'), 'users', 'users', ['blocked_by_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_blocked_by_admin_id_users'), 'users', type_='foreignkey')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'blocked_by_admin_id')
    op.drop_column('users', 'blocked_at')
    op.drop_column('users', 'blocked_reason')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'role')
    op.drop_constraint(op.f('fk_ratings_deleted_by_user_id_users'), 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'delete_reason')
    op.drop_column('ratings', 'deleted_by_user_id')
    op.drop_column('ratings', 'deleted_at')
    op.add_column('events', sa.Column('rating_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_events_rating_count'), 'events', ['rating_count'], unique=False)
    op.create_index(op.f('ix_events_average_rating'), 'events', ['average_rating'], unique=False)
    op.drop_constraint(op.f('fk_comments_deleted_by_user_id_users'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'delete_reason')
    op.drop_column('comments', 'deleted_by_user_id')
    op.drop_column('comments', 'deleted_at')
    op.drop_index('ix_user_activity_logs_user_id', table_name='user_activity_logs')
    op.drop_index('ix_user_activity_logs_action', table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index('ix_audit_logs_target_type_target_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
