"""Add unique constraint to comments

Revision ID: 446f4fb058de
Revises: 20260607_0001
Create Date: 2026-06-07 19:10:48.276574
"""

from typing import Sequence, Union

from alembic import op



revision: str = '446f4fb058de'
down_revision: Union[str, None] = '20260607_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_comments_user_id_event_id', 'comments', ['user_id', 'event_id'])
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_comments_user_id_event_id', 'comments', type_='unique')
    # ### end Alembic commands ###
