"""add parent_event_id

Revision ID: 4fa4d16a7030
Revises: 20260430_0001
Create Date: 2026-04-30 19:08:59.920997
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "4fa4d16a7030"
down_revision: Union[str, None] = "20260430_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("parent_event_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_events_parent_event_id_events"),
        "events",
        "events",
        ["parent_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_events_parent_event_id_events"), "events", type_="foreignkey"
    )
    op.drop_column("events", "parent_event_id")
    # ### end Alembic commands ###
