"""add_auth_profile_ratings_comments

Revision ID: 99d98d0531e8
Revises: 20260527_0001
Create Date: 2026-05-28 16:06:59.452971
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '99d98d0531e8'
down_revision: Union[str, None] = '20260527_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_codes'))
    )
    op.create_index('ix_email_verification_codes_email', 'email_verification_codes', ['email'], unique=False)
    op.create_index('ix_email_verification_codes_user_id', 'email_verification_codes', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_comments_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_event_id', 'comments', ['event_id'], unique=False)
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name=op.f('ck_ratings_ck_ratings_score_range')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ratings_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_ratings_user_id_event_id')
    )
    op.create_index('ix_ratings_event_id', 'ratings', ['event_id'], unique=False)
    op.create_index('ix_ratings_user_id', 'ratings', ['user_id'], unique=False)
    op.drop_index(op.f('ix_events_status_category_date_time'), table_name='events')
    op.drop_index(op.f('ix_events_status_location_date_time'), table_name='events')
    op.drop_index(op.f('ix_events_status_organizer_date_time'), table_name='events')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(length=24), nullable=True))
    op.create_index('uq_users_verified_email', 'users', ['email'], unique=True, postgresql_where=sa.text('is_verified = true'), sqlite_where=sa.text('is_verified = 1'))
    op.create_index('uq_users_verified_nickname', 'users', ['nickname'], unique=True, postgresql_where=sa.text('is_verified = true'), sqlite_where=sa.text('is_verified = 1'))
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_verified_nickname', table_name='users', postgresql_where=sa.text('is_verified = true'), sqlite_where=sa.text('is_verified = 1'))
    op.drop_index('uq_users_verified_email', table_name='users', postgresql_where=sa.text('is_verified = true'), sqlite_where=sa.text('is_verified = 1'))
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.create_index(op.f('ix_events_status_organizer_date_time'), 'events', ['status', 'organizer_name', 'event_date', 'event_time'], unique=False)
    op.create_index(op.f('ix_events_status_location_date_time'), 'events', ['status', 'location', 'event_date', 'event_time'], unique=False)
    op.create_index(op.f('ix_events_status_category_date_time'), 'events', ['status', 'category_id', 'event_date', 'event_time'], unique=False)
    op.drop_index('ix_ratings_user_id', table_name='ratings')
    op.drop_index('ix_ratings_event_id', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.drop_index('ix_comments_event_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_email_verification_codes_user_id', table_name='email_verification_codes')
    op.drop_index('ix_email_verification_codes_email', table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
