"""add_onboarding_state_to_chats

Revision ID: ad694c4c9406
Revises: 2f1f82a9a6c0
Create Date: 2026-06-01 03:39:22.384368
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ad694c4c9406'
down_revision: Union[str, None] = '2f1f82a9a6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('setup_message_id', sa.BigInteger(), nullable=True))
    op.add_column('chats', sa.Column('registration_status', sa.String(length=32), server_default='pending_permissions', nullable=False))
    op.add_column('chats', sa.Column('permissions_status', sa.JSON(), nullable=True))
    op.add_column('chats', sa.Column('categories_selected', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('chats', 'registration_message_id')
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('registration_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('chats', 'categories_selected')
    op.drop_column('chats', 'permissions_status')
    op.drop_column('chats', 'registration_status')
    op.drop_column('chats', 'setup_message_id')
    # ### end Alembic commands ###
