"""Add photo_url to users

Revision ID: 2eaf66765e24
Revises: 20260606_0001
Create Date: 2026-06-06 19:01:26.395804
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2eaf66765e24'
down_revision: Union[str, None] = '20260606_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('photo_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_verified_email_search'), table_name='users')
    op.drop_index(op.f('ix_users_verified_nickname_search'), table_name='users')
    op.drop_column('users', 'language')
    op.drop_column('users', 'language_selected')
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_selected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=2), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_verified_nickname_search'), 'users', ['is_verified', 'nickname'], unique=False)
    op.create_index(op.f('ix_users_verified_email_search'), 'users', ['is_verified', 'email'], unique=False)
    op.drop_column('users', 'photo_updated_at')
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
