"""Add event rating columns

Revision ID: 5ae7877410de
Revises: 20260528_0001
Create Date: 2026-05-29 10:45:39.948547
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5ae7877410de'
down_revision: Union[str, None] = '20260528_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('average_rating', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('events', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_events_average_rating', 'events', ['average_rating'], unique=False)
    op.create_index('ix_events_rating_count', 'events', ['rating_count'], unique=False)
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_rating_count', table_name='events')
    op.drop_index('ix_events_average_rating', table_name='events')
    op.drop_column('events', 'rating_count')
    op.drop_column('events', 'average_rating')
    # ### end Alembic commands ###
