"""add event end time

Revision ID: 62e973abeaa4
Revises: 20260703_0001
Create Date: 2026-07-03 20:44:34.627249
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '62e973abeaa4'
down_revision: Union[str, None] = '20260703_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_end_time')
    # ### end Alembic commands ###
