"""add_it_equipment_materials_to_events

Revision ID: 64dd155ec500
Revises: aef2e2192d51
Create Date: 2026-07-02 22:45:47.069223
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '64dd155ec500'
down_revision: Union[str, None] = 'aef2e2192d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('it_equipment', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('materials', sa.Text(), nullable=True))
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'materials')
    op.drop_column('events', 'it_equipment')
    # ### end Alembic commands ###
