"""add registration_message_id to chat

Revision ID: 9c13158a22e8
Revises: 4fa4d16a7030
Create Date: 2026-05-01 13:52:57.118638
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9c13158a22e8'
down_revision: Union[str, None] = '4fa4d16a7030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# applies this migration
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('registration_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


# reverts this migration
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'registration_message_id')
    # ### end Alembic commands ###
